/** ISO 3166-1 countries and common territories, excluding India (field is residence outside India). */
export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export type CountryName = (typeof COUNTRIES)[number];

const SEARCH_ALIASES: Record<string, string[]> = {
  "United States": ["usa", "us", "america", "united states of america"],
  "United Kingdom": ["uk", "britain", "great britain", "england", "scotland", "wales", "northern ireland"],
  "United Arab Emirates": ["uae", "emirates"],
  "South Korea": ["korea", "republic of korea", "rok"],
  "North Korea": ["dprk"],
  "Czech Republic": ["czechia"],
  "Ivory Coast": ["cote divoire", "côte d'ivoire", "cote d'ivoire"],
  "Democratic Republic of the Congo": ["drc", "congo kinshasa", "zaire"],
  Congo: ["congo brazzaville", "republic of the congo"],
  Russia: ["russian federation"],
  "Hong Kong": ["hk", "hong kong sar"],
  Macau: ["macao", "macao sar"],
  Myanmar: ["burma"],
  Eswatini: ["swaziland"],
  "East Timor": ["timor leste"],
  "Timor-Leste": ["east timor", "timor leste"],
  Netherlands: ["holland"],
  "Vatican City": ["holy see"],
  Palestine: ["state of palestine", "west bank", "gaza"],
  "North Macedonia": ["macedonia"],
  "Cabo Verde": ["cape verde"],
  "South Africa": ["rsa"],
  Germany: ["deutschland"],
  China: ["prc", "people's republic of china"],
  Taiwan: ["roc", "republic of china"],
};

export function countryMatchesQuery(country: string, query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  if (country.toLowerCase().includes(q)) return true;
  const aliases = SEARCH_ALIASES[country] ?? [];
  return aliases.some((alias) => alias.includes(q) || q.includes(alias));
}

export function filterCountries(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [...COUNTRIES];
  const exact = COUNTRIES.some((country) => country.toLowerCase() === q);
  if (exact) return [...COUNTRIES];
  return COUNTRIES.filter((country) => countryMatchesQuery(country, q));
}
